include_guard()

set(vcpkg_submodule "${CMAKE_CURRENT_LIST_DIR}/../external/vcpkg")
set(vcpkg_cmake_subpath "scripts/buildsystems/vcpkg.cmake")
if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED ENV{CADRE_FORCE_LOCAL_VCPKG})
    message(STATUS "Using vcpkg from \"$ENV{VCPKG_ROOT}\"")
    include("$ENV{VCPKG_ROOT}/${vcpkg_cmake_subpath}")
elseif(EXISTS "${vcpkg_submodule}")
    include("${vcpkg_submodule}/${vcpkg_cmake_subpath}")
else()
    message(FATAL_ERROR "Initialize the \"vcpkg\" submodule, or use \"VCPKG_ROOT\" to point to an external clone.")
endif()
